stages:
  - linting
  - test

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
        - pip install -r requirements/test.txt
        - flake8 --verbose .

black:
    stage: linting
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
        - black --check .

test:
    stage: test
    image: 'python:3.12.3'
    script:
      - pip install -r requirements/test.txt
      - cd lyceum
      - python manage.py test
