name: flake8 Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - uses: registry.gitlab.com/black:latest
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "79"
          plugins:
            - "flake8-quotes"
            - "flake8-import-order"
            - "pep8-naming"