stages:
  - linting
  - test

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
        - pip install -r requirements/test.txt
        - flake8 --verbose .

black:
    stage: test
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
        - black --check --verbose -l 79 --skip-string-normalization .
