[tool.black]
line-length = 79
skip-string-normalization = true

[tool.flake8]
exclude=['*/migrations/']
application-import-names='about,catalog,core,download,homepage,lyceum'
import-order-style='google'