[tool.black]
exclude='lyceum/feedback/forms.py'
line-length = 79
skip-string-normalization = true

[tool.flake8]
exclude=['*/migrations/']
application-import-names='about,catalog,core,download,feedback,homepage,lyceum'
import-order-style='google'