[tool.black]
line-length = 79
skip-string-normalization = true

[tool.flake8]
application-import-names=['about', 'catalog', 'catalog.models', 'core.models', 'homepage', 'lyceum']
import-order-style = 'google'