# Generated by Django 4.2.16 on 2024-11-07 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField()),
                (
                    'created_on',
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('received', 'получено'),
                            ('in_progress', 'в обработке'),
                            ('answered', 'ответ дан'),
                        ],
                        default='received',
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'timestamp',
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    'from_status',
                    models.CharField(db_column='from', max_length=20),
                ),
                ('to', models.CharField(max_length=100)),
                (
                    'feedback',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='status_logs',
                        to='feedback.feedback',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=feedback.models.FeedbackFile.upload_to,
                    ),
                ),
                (
                    'feedback',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='feedback.feedback',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackContact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ('mail', models.EmailField(max_length=254)),
                (
                    'contact',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedbacks',
                        to='feedback.feedback',
                    ),
                ),
            ],
        ),
    ]
