# Generated by Django 4.2.16 on 2024-11-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcontact',
            name='contact',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbacks',
                to='feedback.feedback',
            ),
        ),
    ]
