# Generated by Django 4.2.16 on 2024-11-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedbackcontact_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={
                'verbose_name': 'фидбек',
                'verbose_name_plural': 'фидбеки',
            },
        ),
        migrations.AlterModelOptions(
            name='feedbackcontact',
            options={
                'verbose_name': 'контакт фидбека',
                'verbose_name_plural': 'контакты фидбека',
            },
        ),
        migrations.AlterModelOptions(
            name='feedbackfile',
            options={
                'verbose_name': 'фидбек файл',
                'verbose_name_plural': 'фидбек файлы',
            },
        ),
        migrations.AlterModelOptions(
            name='statuslog',
            options={
                'verbose_name': 'лог статуса',
                'verbose_name_plural': 'логи статуса',
            },
        ),
    ]
