# Generated by Django 4.2.16 on 2024-11-11 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            'feedback',
            '0003_alter_feedback_options_alter_feedbackcontact_options_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackfile',
            name='feedback',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='files',
                to='feedback.feedback',
                verbose_name='',
            ),
        ),
        migrations.AlterField(
            model_name='feedbackfile',
            name='file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=feedback.models.FeedbackFile.upload_to,
                verbose_name='',
            ),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='from_status',
            field=models.CharField(
                db_column='from', max_length=20, verbose_name='старый статус'
            ),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='timestamp',
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name='время изменения'
            ),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='to',
            field=models.CharField(
                max_length=100, verbose_name='новый статус'
            ),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
    ]
