# Generated by Django 4.2.16 on 2024-11-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_coffee_count_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coffee_count',
            field=models.PositiveIntegerField(
                default=0, verbose_name='счетчик кофе'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='uploads/',
                verbose_name='аватарка',
            ),
        ),
    ]
