# Generated by Django 4.2.16 on 2024-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attempts_count',
            field=models.PositiveIntegerField(
                default=0, verbose_name='счетчик попыток'
            ),
        ),
    ]
