# Generated by Django 4.2.16 on 2024-10-13 11:18

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                ('is_published', models.BooleanField()),
                (
                    'name',
                    models.CharField(max_length=150, verbose_name='Название'),
                ),
                (
                    'text',
                    models.TextField(
                        validators=[catalog.validators.CustomValidator]
                    ),
                ),
            ],
        ),
    ]
