# Generated by Django 4.2.16 on 2024-10-23 17:34

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='статус `опубликовано`',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='напишите сюда название',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'normalized_name',
                    models.CharField(
                        editable=False,
                        max_length=150,
                        unique=True,
                        verbose_name='нормализованное имя',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='напишите слаг',
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[a-zA-Z0-9_-]*$'
                            )
                        ],
                        verbose_name='слаг',
                    ),
                ),
                (
                    'weight',
                    models.IntegerField(
                        default=100,
                        help_text='выбирите вес',
                        validators=[
                            django.core.validators.MaxValueValidator(32767),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name='вес',
                    ),
                ),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='статус `опубликовано`',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='напишите сюда название',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='напишите необходимый текст',
                        validators=[
                            catalog.validators.CustomValidator(
                                'превосходно', 'роскошно'
                            )
                        ],
                        verbose_name='текст',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='category_items',
                        to='catalog.category',
                    ),
                ),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='статус `опубликовано`',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='напишите сюда название',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'normalized_name',
                    models.CharField(
                        editable=False,
                        max_length=150,
                        unique=True,
                        verbose_name='нормализованное имя',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='напишите слаг',
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[a-zA-Z0-9_-]*$'
                            )
                        ],
                        verbose_name='слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='SecondImages',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        help_text='Выберите изображение',
                        upload_to='uploads/',
                        verbose_name='Будет приведено к размеру 300х300',
                    ),
                ),
                (
                    'images',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catalog.item',
                        verbose_name='изображения',
                    ),
                ),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'main_images',
                    models.ImageField(
                        default='/static/img/enot.jpg',
                        help_text='Выберите изображение',
                        upload_to='uploads/',
                        verbose_name='Будет приведено к размеру 300х300',
                    ),
                ),
                (
                    'main_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='mainimage',
                        to='catalog.item',
                        verbose_name='главное изображение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                to='catalog.tag', verbose_name='теги'
            ),
        ),
    ]
