# Generated by Django 4.2.16 on 2024-10-15 21:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import catalog.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='статус `опубликовано`',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='напишите сюда название',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='напишите слаг',
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[a-zA-Z0-9_-]*$',
                            ),
                        ],
                        verbose_name='слаг',
                    ),
                ),
                (
                    'weight',
                    models.IntegerField(
                        default=100,
                        help_text='выбирите вес',
                        validators=[
                            django.core.validators.MaxValueValidator(32767),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name='вес',
                    ),
                ),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='статус `опубликовано`',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='напишите сюда название',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='напишите слаг',
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[a-zA-Z0-9_-]*$',
                            ),
                        ],
                        verbose_name='слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='статус `опубликовано`',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='напишите сюда название',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='напишите необходимый текст',
                        validators=[
                            catalog.validators.CustomValidator(
                                'превосходно',
                                'роскошно',
                            ),
                        ],
                        verbose_name='текст',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='category_items',
                        to='catalog.category',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        to='catalog.tag',
                        verbose_name='теги',
                    ),
                ),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
