# Generated by Django 4.2.16 on 2024-10-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainimage',
            options={
                'verbose_name': 'превью',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='main_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='item_main_img',
                to='catalog.item',
                verbose_name='главное изображение',
            ),
        ),
    ]
