# Generated by Django 4.2.16 on 2024-10-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(
                editable=False,
                max_length=150,
                unique=True,
                verbose_name='нормализованное имя',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(
                editable=False,
                max_length=150,
                unique=True,
                verbose_name='нормализованное имя',
            ),
        ),
    ]
