# Generated by Django 4.2.16 on 2024-10-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_normalized_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to='uploads/', verbose_name='изображение'
                    ),
                ),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='images',
                to='catalog.mainimage',
                verbose_name='изображения',
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.mainimage',
                verbose_name='главное изображение',
            ),
        ),
    ]
