# Generated by Django 4.2.16 on 2024-10-14 17:25
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'catalog',
            '0003_category_tag_alter_item_options_item_is_published_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.category',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='catalog.tag'),
        ),
    ]
