# Generated by Django 4.2.16 on 2024-10-24 18:51

import catalog.validators
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_mainimage_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text='напишите необходимый текст',
                validators=[
                    catalog.validators.CustomValidator(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='текст',
            ),
        ),
    ]
