# Generated by Django 4.2.16 on 2024-10-14 21:11

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_category_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='статус `опубликовано`',
                verbose_name='Опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='напишите сюда название',
                max_length=150,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(
                help_text='напишите слаг',
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator('^[a-zA-Z0-9_-]*$')
                ],
                verbose_name='Слаг',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(
                default=100,
                help_text='выбирите вес',
                validators=[
                    django.core.validators.MaxValueValidator(32767),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name='Вес',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.category',
                verbose_name='Категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='статус `опубликовано`',
                verbose_name='Опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='напишите сюда название',
                max_length=150,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                to='catalog.tag', verbose_name='Теги'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                help_text='напишите необходимый текст',
                validators=[catalog.validators.CustomValidator],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='статус `опубликовано`',
                verbose_name='Опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='напишите сюда название',
                max_length=150,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(
                help_text='напишите слаг',
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator('^[a-zA-Z0-9_-]*$')
                ],
                verbose_name='Слаг',
            ),
        ),
    ]
