# Generated by Django 4.2.16 on 2024-10-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_main_images_mainimage_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='main_image',
                to='catalog.item',
                verbose_name='главное изображение',
            ),
        ),
    ]
