# Generated by Django 4.2.16 on 2024-10-30 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_main_images_mainimage_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(
                editable=False,
                max_length=150,
                verbose_name='нормализованное имя',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='category_items',
                related_query_name='category_items',
                to='catalog.category',
            ),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='main_image',
                related_query_name='main_image',
                to='catalog.item',
                verbose_name='главное изображение',
            ),
        ),
        migrations.AlterField(
            model_name='secondimages',
            name='images',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='images',
                related_query_name='images',
                to='catalog.item',
                verbose_name='изображения',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(
                editable=False,
                max_length=150,
                verbose_name='нормализованное имя',
            ),
        ),
    ]
