# Generated by Django 4.2.16 on 2024-10-30 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            'catalog',
            '0007_alter_category_normalized_name_alter_item_category_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='category',
                related_query_name='category',
                to='catalog.category',
            ),
        ),
    ]
